services:
  mysql:
    image: mysql:8.0
    container_name: taskflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskflow_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskflow-network

  backend:
    image: luthirapeiris/taskflow-backend:${IMAGE_TAG}
    container_name: taskflow-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: taskflow_db
      JWT_SECRET: taskflow_secret_key
    depends_on:
      - mysql
    networks:
      - taskflow-network

  frontend:
    image: luthirapeiris/taskflow-frontend:${IMAGE_TAG}
    container_name: taskflow-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - taskflow-network

volumes:
  mysql_data:

networks:
  taskflow-network: